### ISSUE TITLE
Import new language option

### ISSUE THREAD

**Issue by Mycheze** [jzohrab/lute-v3#10]
**Is your feature request related to a problem? Please describe.**

Not all languages are supported and the regex/link stuff isn't possible for "non-techies."

**Describe the solution you'd like**

When adding a new language, there's the option to "load from predefined." It would be a great "stepping stone" if there was a simple text file that could be made and shared to "import" languages according to the settings that work well for another user. 

This could also allow for more "default" languages to be supported if they're just a small text file that can be downloaded and added to future releases. 

**Describe alternatives you've considered**

**Additional context**

This is how a file might look:
[czechlanguagelute.txt](https://github.com/jzohrab/lute/files/12553463/czechlanguagelute.txt)

**Comment by jzohrab** [comment]
In v3, language creation and addition is pretty simple now.  The docs have a simple page (https://jzohrab.github.io/lute-manual/faq/add-a-language.html) that redirect to a new issue type -- https://github.com/jzohrab/lute-v3/issues/new?assignees=&labels=enhancement&projects=&template=add_language.md&title=Add+language%3A+%5Bname%5D

It's not _exactly_ what is requested in this ticket, but this ticket is such an amount of work for such a _very small_ group of people, and such a _very small_ savings of effort for those users, that I'm going to close it in order to keep more focused on existing issues.  @Mycheze if you disagree then we can reopen it.  Cheers!
