### ISSUE TITLE
Dont show terms that are children themselfs as suggestion when adding a term.

### ISSUE THREAD

**Issue by dgc08** [jzohrab/lute-v3#106]
If you want to add a parent to a term, there will be suggestions when you start to type. The problem is, the different forms of a word start in almost all languages(I think) the same as the base form, so forms that have a parent themself get showed too. Adding terms that are not the "base form" as a parent makes no sense, because you would add the parent of that term as parent instead.

Example:
![image](https://github.com/jzohrab/lute-v3/assets/83305972/b33e783f-c837-42ca-aac6-802c45fbbb41)

A problem might be that some users add the term itself as parent to the term (if the term is the base form. Thats why I would say, only show terms that have either themselfs or nothing as parent in the suggestions.

**Comment by jzohrab** [comment]
I don't think I'm going to fix this, because I actually use this as you've shown here ... For example, in Spanish (and probably other languages), there are many adjectives that are forms of verbs.  I sometimes have the feminine form of the adjective use the masc as the parent, and then the masc adjective has the verb as the parent.

Now, this might be a very dumb way for me to be managing this!  I don't know -- and I don't mind enough to be concerned about it.  I don't look at the data in Lute as a "good definition", I just use it as my own notebook, in a way.

Users can't set a term as its own parent, they get removed on save.

Any parents get sorted to the top of the list, so at least they're easier to pick out.
