### ISSUE TITLE
[Feature] Ability to delete a term from reading screen.

### ISSUE THREAD

**Issue by disfated** [jzohrab/lute-v3#13]
It is occasionally needed to be able to remove a term while staying on the reading page.

**Comment by jzohrab** [comment]
Just adding a "delete" button next to the "Save" button would suffice as a first pass:

![Image](https://github.com/jzohrab/lute-v3/assets/1637133/fa449149-6712-44bc-98db-20dee3206b87)

A few caveats:

* if reading, this should trigger a page reload so that all of the parsed tokens are rendered correctly
* if on the term form, this should redirect to the term listing
* should show a warning that this can't be undone.  In particular, if a term has children, those will be orphaned and any parent description will be lost.  Perhaps an extra warning for parents would be good.

**Comment by jzohrab** [comment]
Fixed in #85 , merged into develop.

**Comment by jzohrab** [comment]
Launch in 3.0.9.
