### ISSUE TITLE
Word status tracking parent status 

### ISSUE THREAD

**Issue by PsychoThinker** [jzohrab/lute-v3#131]
Shouldn't the status of the word and its parent change at the same time?

It seemed to me that the whole point of this functionality was to be able to link different conjugations to a common parent and change statuses/translations in one place.

**Comment by jzohrab** [comment]
The initial point of the parents was to allow for entering the translation/meaning only once, and have that value be inherited and shown in the term hover.  For me that was always the huge pain point.

I didn’t think that status linking was as important, but others requested it, so it’s spec’d out in https://github.com/jzohrab/lute-v3/issues/66 and I’m working on it now.

I think this issue is a duplicate, please close it if so. Thanks!

**Comment by PsychoThinker** [comment]
Oh, sorry, I hadn't noticed. Thanks for letting me know.
