### ISSUE TITLE
Set “Words per page” for all books

### ISSUE THREAD

**Issue by GrimPixel** [jzohrab/lute-v3#254]
**Is your feature request related to a problem? Please describe.**

It takes the efforts to set “Words per page” each time importing a book. Once set, it is unchangeable.

**Describe the solution you'd like**

Set “Words per page” for all books instead of each book individually.

**Comment by jzohrab** [comment]
Pruning the backlog of issues :-)  I won't do this one, for the reasons below.

* The defaults should suffice, you don't _have_ to change it.
* It's unchangeable once set because it breaks the text up into several pages.  Changing it would effectively require a reparse of the book, which could be a hassle.
* People want to set the page sizes individually, depending on the material and language.  If I'm a beginner, I want very few words per page, b/c I don't have the energy to process piles of information.  As I improve, I'll want to increase it.

Cheers, sorry but not every issue can really be considered, because it's open source and everyone is different.
