### ISSUE TITLE
Pop-up window in new tab, not new window

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-v3#295]
Currently, for me, t or shift-t opens a new window. I did some searching and this may be a user setting, but I'm using the latest version of Firefox on Windows, and `Open links in tabs instead of new windows` is checked in the Firefox settings (and is the default behaviour elsewhere).

So:

1. For others, does it open in a new tab or a new window?
2. If it's always a new window, is it possible to change this to a new tab - or at least adding this as an option (e.g. Embedded, Pop-up window, New tab).

I thought it related to `_load_popup` within `dict-tabs.js`, but my quick testing changing the config of `window.open` didn't seem to work (but equally that could just be me!)

**Comment by jzohrab** [comment]
1. For me, it opens as a new window -- with the current code, it should always open as a new window.

2. Adding it as an option as you mentioned seems clearest.  The js needs some work to support it, we ported it with some ugly stuff just because it was expedient, but we should change it anyway for clarity.  When we do, your suggestion will be much easier to implement.

> my quick testing changing the config of window.open didn't seem to work

hm, that should have worked, I'll check.

**Comment by jzohrab** [comment]
@jamesdeluk - making the following change to dict-tabs.js, and then _reloading the reading page_, worked for me:

```
  _load_popup(url, term) {
    if ((url ?? "") == "")
      return;
    if (url[0] == "*")  // Should be true!
      url = url.slice(1);
    const lookup_url = this._get_lookup_url(url, term);
    window.open(
      lookup_url,
      'otherwin'
      /* ,  // commenting out all config stuff
         'width=800, height=600, scrollbars=yes, menubar=no, resizable=yes, status=no'
         */
    );
  }
```

On second though, rather than have it be an option like "embedded, pop-up, new tab", perhaps better would be a User Option from settings that says "Open lookup pop-ups in fullsize window" or something instead, and then users would have to configure their browsers to open these as tabs or not.  This would probably suffice, and it would be much easier to implement given the current code.  @jamesdeluk does that seem all right?

**Comment by jzohrab** [comment]
Dev size estimate notes:

* add UserOption
* figure out where to put it in user settings UI -- this is like a new section, page needs layout
* dict-tabs.js would need to get the user setting and use it -- are settings already output into the global JS space?  If not, consider doing that for future things
* change _open_window thing

**Comment by jamesdeluk** [comment]
The edit didn't work for me; I have Lute installed with pip and was simply editing `\Lib\site-packages\lute\static\js\dict-tabs.js`, maybe that's why?

Yes, maybe an "open in popup" / "open full size" option might work well.

**Comment by jzohrab** [comment]
hmm ... should have worked.  I assume you refreshed the page.  The js might also be cached ... keep trying with the edit, maybe you can get it to stick as a workaround until the option is added.

Regardless, the option should suffice.

**Comment by jamesdeluk** [comment]
Still nope. According to the debugger, I'm using the updated dict-tabs. I also added a console.log and an alert at the beginning of _load_popup, but they didn't show. Strange. Then again, as I've said elsewhere, I'm not a developer, I just hack at things haha.

**Comment by jzohrab** [comment]
hm ... ok then something else is being used, if your alerts aren't being shown.

> I'm not a developer, I just hack at things haha

Well, I used to be a dev, and I still just hack at things. :-D

Anyway, the user option seems like a decent enough idea.  Sorry you'll have to wait until it's ready.  No time. :-P

**Comment by jzohrab** [comment]
Hey there I had to fix something else so this will be in develop soon and in the next release.

In the "settings" there's now a section:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/9e0a58d8-e349-4d27-99c6-24853e647d1b)

I've tried it out on my machine, seems to work fine.  e.g. with the default unchecked setting, it's a popup:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/f6f71445-2749-4484-b940-1afb5987a57c)

and with it checked (Save after checking), it's a tab:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/3f3fa12d-c02d-4996-a19e-31005075a668)
