### ISSUE TITLE
Sort terms by "order added"

### ISSUE THREAD

**Issue by Adriann25** [jzohrab/lute-v3#305]
Currently, terms can only be sorted alphabetically or by parent term, translation, language, tags or status.

It is, however, as of writing this issue not possible to sort terms by "order added/saved" which creates an issue for languages like Japanese and Chinese where there is no alphabetical order to begin with and for "books" that would require some continuity when exporting terms, such as film scripts, song lyrics, poems, etc.

It'd be nice if there was a way to simply sort terms by the order they were saved in.

Alternatively, there could be either a column for sorting by date instead of order added or one that sorts by the term's placement in a particular book, but that might be more difficult to implement for essentially the same result (most people add terms in order of the book they created).

**Comment by jamesdeluk** [comment]
Agreed, would it very useful.

Also relates to https://github.com/jzohrab/lute-v3/issues/24

**Comment by jzohrab** [comment]
I added "date added" in a branch, not yet merged to mainline, which looks like this:

> <img width="1626" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/913a630a-1679-4c5f-883b-a99ea08d4b69">

I'm reluctant to add the term ID, which more or less equates to the "order added", because it really looks like clutter in the page.

I don't understand "... require some continuity when exporting terms, such as film scripts, song lyrics, poems, etc" -- why do you want to export terms in the order they occur in a book?  Just curious.

**Comment by Adriann25** [comment]
> I'm reluctant to add the term ID, which more or less equates to the "order added", because it really looks like clutter in the page.

That's understandable, although now even if you have the "added" column, I assume it still defaults to alphabetical order if the date is the same, which was not my intention. I know I'm asking a lot, but is there a way to, if not adding the term ID, to make it export the terms by the exact order they were created in?
> I don't understand "... require some continuity when exporting terms, such as film scripts, song lyrics, poems, etc" -- why do you want to export terms in the order they occur in a book? Just curious.

Well, when exporting them, you would want them to be in the order of the "book" so that you can go over and add audio/video context from the source material to them on the end platform. Also, when learning the terms you'd ideally not have them in alphabetical order, because it inhibits retention if you have similar-ish terms one after another. And with languages like Chinese and Japanese, the "alphabetical" order, makes it so that all the one-character terms are at the bottom and all the 4+ character terms are at the top, which is very inefficient from a learning perspective.

**Comment by jzohrab** [comment]
Hey @Adriann25 , thanks for the extra detail, that's helpful.

>   I assume it still defaults to alphabetical order if the date is the same, which was not my intention

I'm actually not sure what it does :-P -- Currently, I just have the query export the "date" portion of the datetime, but that would mean that things would be mixed up, even slightly.  The full date/time data is present in the db though, e.g.:

```
sqlite> select wotext, WoCreated from words;
gato|2024-03-08 21:59:26
perro|2024-03-08 21:59:28
these|2024-03-08 22:06:02        <---- fyi The last 4 are the exact same because I did a bulk update.
are|2024-03-08 22:06:02
because|2024-03-08 22:06:02
unknown|2024-03-08 22:06:02
```

2 points:

* Perhaps what should work would be to export the full value for the sorting, but when showing it on screen, only show the date part, and then hover over could have the full information (so all these terms would say "2024-03-08", but you'd hover to see the specifics).  Then things should sort correctly, I'll try that out.
* The CSV export currently doesn't include the date/time, but I could add that so that you could sort it however you wanted.

How about we try that as a first pass, after I make the necessary tweaks?  Your request makes sense, so I'd like to get you a "minimum viable solution" that will do, so that I can make progress on other fronts.

**Comment by Adriann25** [comment]
> How about we try that as a first pass, after I make the necessary tweaks? Your request makes sense, so I'd like to get you a "minimum viable solution" that will do, so that I can make progress on other fronts.
Ok sure. Will have to test it out and see how it behaves regardless, but I think this should do; at most, I'd just have to create a new column on Anki and assign it to a field based on the date/time column. Whichever way you see as easier to implement, as long as it results in the desired outcome is fine with me.

**Comment by jzohrab** [comment]
ok.  Here's a sample CSV export snippet:

```
term,parent,translation,language,tags,added,status,link_status,pronunciation
gato,,cat,Spanish,,2024-03-09 04:59:26,1,,
perro,,cat,Japanese,,2024-03-09 04:59:28,1,,
```

Here's the UI, "perro" sorts 2nd, hover over it to see the time:

> <img width="700" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/3f5a67be-bf01-43ce-b6f3-fbc98c7ff108">

Should suffice, not too noisy, thanks.  Just have to update some tests and all good.

**Comment by Adriann25** [comment]
I agree, looks perfect from what I can tell, thank you for implementing it. Will leave closing the issue to you after you add it to the main branch.

**Comment by jzohrab** [comment]
Merged the branch into `develop`, it will be in the next launch (maybe next week or so?)

**Comment by jzohrab** [comment]
Launched in 3.2.5.
