### ISSUE TITLE
Add ability to save any terms in language from reading page

### ISSUE THREAD

**Issue by mzraly** [jzohrab/lute-v3#311]
**Is your feature request related to a problem? Please describe.**

When reading a book I often come upon a form of a word that I want to save as the child of a parent that doesn't yet exist.  I want to be able to save both, with the link between parent and child, with appropriate pronunciation, translation, familiarity, and tag values.

I cannot put arbitrary data in the Term field.  If I do, when I try to save I get tan error message saying "Can only change term case"

To work around this, I have to open the Terms page in a separate tab, add the desired parent term, then either add the child term in the Terms page and go back to the book, or go back to the book and add the child term there.

A related use case is adding sibling terms, e.g. by changing the term to use different gender and number affixes.

**Describe the solution you'd like**

Disable the check for changes in the term field before saving.  Let the user save whatever he or she wants without restriction.

After changing the value in the term field, if there is already an entry in the terms database for that value, load data from that entry into the dialog so the user can make edits.

**Describe alternatives you've considered**

1. Change the behavior of the check to issue a warning that the term has been saved with a different name, and provide an Undo button to revert the save operation.  This would require remembering the previous state of the term somehow.

2. Change the behavior of the check to raise a modal dialog that lets the user abort or continue.

**Additional context**

None

**Comment by jzohrab** [comment]
Hi @mzraly - thanks for taking the time to write this.

> When reading a book I often come upon a form of a word that I want to save as the child of a parent that doesn't yet exist. I want to be able to save both, with the link between parent and child, with appropriate pronunciation, translation, familiarity, and tag values.

Lute seems to already do this -- if you enter a new parent, it gets created with the same data as the term.  See the manual: https://jzohrab.github.io/lute-manual/usage/terms/parent-terms.html#defining-a-term-and-a-new-parent  -- I wrote it this way b/c when I was reading, I wanted to create the linkage, but didn't want to stop the flow.  It's not _perfect_ but it's totally good enough.

Here's an example with the tutorial:

> <img width="500" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/8cc86ce8-241e-4022-9623-1b15c92194cb">

After I save, the parent term is also created, with the data of the child term:

> <img width="206" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/e57ab6bc-7eda-47a1-9ba8-47d10bbad9cf">

Granted, you'd have to go into the parent to update it if you wanted to put some specific information in there, but after lots of usage of Lute, I've found that I really don't care in most cases!

Is this sufficient?

> Disable the check for changes in the term field before saving. Let the user save whatever he or she wants without restriction.

This isn't possible for a few reasons -- basically, a Term entity's text is "immutable" (except for capitalization) because allowing it to change could create weird cases, such as a parent term being changed to something completely different.  We'd need to create a different entry mechanism (e.g. a "create new term" button or something) -- but maybe this isn't necessary given the notes above about how Lute can auto-create parents.

Cheers, let me know your thoughts!

**Comment by mzraly** [comment]
Hmm, I see auto-saving parents doesn't work if I just copy the root into the parents field, I have to hit another key to turn it into a tag.  Otherwise the new term is saved without the parent being set.  Should text in the parents field automatically turn into a tag when saving?  It's frustrating to have text in the parents field and the Save button succeed but not have the text saved as a parent.

I changed the title of this issue from "save related terms" to "save any terms" because when looking up words I often come across multiple items that I want in the dictionary -- different forms, example phrases, etc.  But having the ability to launch a new tab that I can use to access the Terms page (#312) helps.

So to answer your question, I can live with entering other terms in the Terms page once #312 is available,

**Comment by jzohrab** [comment]
Yes you have to hit return to signal the tag can be made.  #312 will be launched pretty soon i think.  👋

**Comment by jzohrab** [comment]
Closing this as completed, given that #312 will be launching v soon, hopefully today.
