### ISSUE TITLE
Improve backup visibility

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute-v3#37]
I want to know about my backups:

- show listing of files
- show size of backups

**Comment by sakolkar** [comment]
Performed a first pass on this ticket.


#### Backup drop down in the navigation
* Adjusted to have a "time since" description to quickly get a sense of duration since the last backup. Sometimes converting the date directly take a bit more effort.
* Also, the create new backup has been moved into the backups listing page
* There is a link to go to the backups listing page
![image](https://github.com/jzohrab/lute-v3/assets/9434751/8e399564-c708-436c-bf03-f8b2528aa758)


#### Backup listing page
* Sorted with most recent backup at the top of the list
* Shows manual and automated backups in the same table
* Human readable size of the backup file
* Last modified on the file. Created on is a little more nuanced and requires a different method for each OS so I didn't include that.
![image](https://github.com/jzohrab/lute-v3/assets/9434751/570b392c-4187-4e71-9a69-686beb37794e)

**Comment by jzohrab** [comment]
pr merged, thanx @sakolkar , it's exactly what I wanted for myself :-)
