### ISSUE TITLE
New Feature Request: Refresh Stats (i.e. store WordCount in the `texts` table)

### ISSUE THREAD

**Issue by RamSury** [jzohrab/lute-v3#95]
**Is your feature request related to a problem? Please describe.**

Currently, if the content is edited within books (i.e. content is added or deleted), it does not automatically update statistics for the book. The word count still shows the same as before. 

**Describe the solution you'd like**

It would be good to have a refresh statistics button in the Statistics page (http://localhost:5000/stats/) so a stats refresh can be triggered on demand for all books after they are updated.

**Describe alternatives you've considered**

No alternatives available.

**Additional context**

None

**Comment by jzohrab** [comment]
Currently, for some reason, I only track word count at the book level, when the book is created.  Field: `books.BkWordCount`.

Word count is also tracked in the `texts.TxWordCount`, but is only populated when a page is marked read -- this change happened as the code grew.

What should happen: on book creation, the word count should be stored in `TxWordCount`, and just summed for displaying the book stats, no need to store it separately.

Unfortunately this change will require the books to all have their stats calculated.

* Possible solution: store "book stats calculated" flag in system settings, and if that flag is not present and there are texts with null TxWordCount, then calc all the counts and set the flag.  Set the flag at the end of the routine regardless so it's not re-calculated.
* Actually, instead of this, the start-up routine could just do a check for texts with null count, and then calculate the counts.  No need for a flag, no need for anything, just do a one-time update, and show a message that this is being done at start up.

**Comment by jzohrab** [comment]
Fixed in the `develop` branch.  Word counts in texts are stored at the text level, and update if the text is updated.

This was low priority but still good to get done.  Thanks :-)

**Comment by jzohrab** [comment]
Launched in 3.1.1
